### ISSUE TITLE
bug in xval DAPC server - max nb PCs 

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#11]
In the dapc server X val, setting the max number of PCs to less than the default triggers an error.

**Comment by thibautjombart** [comment]
Caitie I'll leave this one to you yeah?

**Comment by thibautjombart** [comment]
Caitie, reply please?

**Comment by thibautjombart** [comment]
Caitlin, can you please check this?

**Comment by caitiecollins** [comment]
Hey,

I thought I had gotten back to you on this somewhere else. It wasn't
actually a bug in the server: it was a bug in the function itself!
I pushed it, if you check via gitk, on April 9th, under "resolved xvaDapc
max.n.pcs issue". What next steps should I take to see this issue is
resolved?

Thanks,
CC

**Comment by thibautjombart** [comment]
Cool! 
You can just close it by clicking on the 'close and comment' below. 
Like.. this!
