### ISSUE TITLE
duplicate row.names not allowed

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#116]
Sometimes one may have duplicate samples in a genind object (i.e. during bootstrapping). Converting to `data.frame` is hindered because of duplicate row names (due to [this](https://github.com/thibautjombart/adegenet/blob/master/R/export.R#L164) and [this](https://github.com/thibautjombart/adegenet/blob/master/R/export.R#L153)). 

Do we want to handle this in adegenet, or should one take care of this individually before passing data to `genind2df`?

```r
library(adegenet)
data(nancycats)

x <- nancycats[c(1,1, 2, 3, 4)]
genind2df(x, sep = " ")

 Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed In addition: Warning message:
non-unique value when setting 'row.names': ‘N215’ 
```

**Comment by thibautjombart** [comment]
Ideally, duplicated labels should be avoid because they are baaad.
Bootstrap changes this, indeed, but still. For `genind2df` we could just
add a simple procedure checking for unique labels and replacing with
generic labels with a warning whenever needed?

Cheers
Thibaut


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by zkamvar** [comment]
:+1:

**Comment by romunov** [comment]
Based on comments from 117, I agree that we let person constructing a genind object from data with duplicate individual names to handle this issue.
