### ISSUE TITLE
find.clusters & optim.a.score

### ISSUE THREAD

**Issue by andrebolerbarros** [thibautjombart/adegenet#122]
1-When I use the function "find.clusters", and retaining enough PC's to explain all variance, the number of clusters and their respective BIC change everytime I run the function. Could this be explained due to my data not having clear clusters or is there something else? I am asking this because it does not seem normal to me....

2- In one paper, I read that "optim.a.score" and "xvalDapc" functions are used for crossed validation. Since the values for optimal PC's are very different and the visual results are also different, and since it is stated that "optim.a.score" is still in development, my question is if it is safe to use "optim.a.score" and, in your opinion, what is the best solution for optimal retained PC's?

**Comment by romunov** [comment]
1) Clustering is done via k-means and if you look at [line 90](https://github.com/thibautjombart/adegenet/blob/master/R/find.clust.R#L90) you will notice that the start is chosen randomly. Since function starts building a cluster randomly, clusters may be different, especially if, like you predicted, they are not  very clear-cut.

A small point - to explain all variance in PCA, you have to retain all principal components. If you retain only a subset you say "these PCs explain my dataset well enough".

**Comment by andrebolerbarros** [comment]
Thanks for the explanation! 

Any clue about number 2, what is better: optim.a.score or xvalDapc? It's just because the first one clearly states we should contact the author before publishing our results...

Thanks yet again

**Comment by caitiecollins** [comment]
Hi there,

A good question, to be sure. I was about to ramble off into an answer, when
I remembered that I've actually done so before here
<http://lists.r-forge.r-project.org/pipermail/adegenet-forum/2014-September/000963.html>
.

I should say, because you may find this useful for the future, that I found
the link to that post in the forum archives by searching "optim.a.score
xvalDapc" in the adegenet forum search engine
<http://adegenet.r-forge.r-project.org/search.html>.

Hope that helps!

All the best,
Caitlin.
