### ISSUE TITLE
Issue on SPCA

### ISSUE THREAD

**Issue by ewicker** [thibautjombart/adegenet#183]
Dear Thibault,
I tried to perform a simple sPCA, tried several connection networks, and obtained the same error message:

```
#  PLEASE NOTE:  The components "delsgs" and "summary" of the
 object returned by deldir() are now DATA FRAMES rather than
 matrices (as they were prior to release 0.0-18).
 See help("deldir").
 
     PLEASE NOTE: The process that deldir() uses for determining
 duplicated points has changed from that used in version
 0.0-9 of this package (and previously). See help("deldir").


Error in .Fortran("master", x = as.double(x), y = as.double(y), rw = as.double(rw),  : 
  "master" not available for .Fortran() for package "deldir"
#
```

I use ADEGENET version 2.0.1. THe script I use used to work, so I don't understand.
THank you in advance for your help, 
Emmanuel Wicker

**Comment by romunov** [comment]
Can you provide a reproducible example?

**Comment by thibautjombart** [comment]
Hello, 
this looks like an issue in registering Fortran routines in the package `deldir`, so unrelated to `adegenet`. Can you report this to the maintainer of this package? It most likely has to do with the new way enforced by CRAN for declaring foreign code routines since R 3.4.0. I had to fix it myself in adegenet a few commits ago.
