### ISSUE TITLE
Missing dependency of stringi

### ISSUE THREAD

**Issue by V-Z** [thibautjombart/adegenet#189]
Hello,
I installed adegenet like this (R 3.4.1, Linux):

    install.packages(pkgs="adegenet", dependencies=c("Depends", "Imports"))

and it failed with an error:

    Error in dyn.load(file, DLLpath = DLLpath, ...) :
    unable to load shared object '/home/vojta/R/x86_64-suse-linux-gnu-library/3.4/stringi/libs/stringi.so':
    libicui18n.so.58.2: cannot open shared object file: No such file or directory
    ERROR: lazy loading failed for package ‘adegenet’`

After manual installation of `stringi` package installation of adegenet worked as expected.

**Comment by zkamvar** [comment]
Hello, 

Thank you for the report. This is actually a nested dependency issue. Adegenet imports reshape2, which imports stringr, which imports stringi. I'm afraid it's turtles all the way down. 

This issue has been encountered many times before across packages. This thread leads to another that has some good advice regarding that: https://github.com/hadley/evaluate/issues/73#issuecomment-269383238

One way to avoid this problem is by updating all packages indiscriminately:

```r
update.packages(ask = FALSE)
```

As this is not explicitly an adegenet issue, I will close this.

**Comment by V-Z** [comment]
Thank You for answer. So there is no way how adegenet could deal with this to avoid installation failure? If so, this workaround must be enough...

**Comment by zkamvar** [comment]
> So there is no way how adegenet could deal with this to avoid installation failure?

Not really, unfortunately. This issue is independent of adegenet's capabilities.  It often occurs when R updates, which is why updating packages regularly is a good idea.
