### ISSUE TITLE
Adegenet failure to load

### ISSUE THREAD

**Issue by Jvplanz** [thibautjombart/adegenet#204]
Tried to load adegenet today and received following error statements:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘dplyr’
In addition: Warning messages:
1: package ‘adegenet’ was built under R version 3.1.3 
2: package ‘ade4’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘adegenet’

How to fix??
JVP

**Comment by romunov** [comment]
@Jvplanz you will have to install package `dplyr`. `install.packages("dplyr")`

**Comment by Jvplanz** [comment]
Hi Roman
I tried that too…I get:

> dplyr.install.packages("dplyr")
Error: could not find function "dplyr.install.packages"


John


John V. Planz, Ph.D.
Associate Professor
Department of Molecular Cell Biology and Genetics
Graduate School of Biomedical Sciences
UNT Health Science Center
3500 Camp Bowie Blvd, CBH 360
Fort Worth, TX 76107
817-735-2397

**Comment by romunov** [comment]
Please make sure you get the function name correct. There is no `dplyr` in function `install.packages`.

**Comment by Jvplanz** [comment]
Thanks Roman…It’s a Monday for sure
Best
John


John V. Planz, Ph.D.
Associate Professor
Department of Molecular Cell Biology and Genetics
Graduate School of Biomedical Sciences
UNT Health Science Center
3500 Camp Bowie Blvd, CBH 360
Fort Worth, TX 76107
817-735-2397

**Comment by romunov** [comment]
Looking at the [CRAN repository](https://cran.r-project.org/web/packages/dplyr/index.html), it says `dplyr` wants R of version 3.1.2 or higher. You're a bit out of luck, I guess. You have two options.

Either upgrade R, which is preferred option. Everything should work out of the box, hopefully.

Or, you can install package from source. This would mean you need to prepare the toolchain. On windows, this would include Rtools and LaTeX (I think). Then, you would download the source file and install using `install.packages("path to file.gz", type= "source")`. This is not guaranteed to work since some packages may depend on specific version of other packages. Go with option 1. :)

**Comment by Jvplanz** [comment]
Thanks a bunch Roman…I haven’t run R in a while so it is clearly in need of updating…never thought of that until now
Thanks for all your help
Have a great day
John


John V. Planz, Ph.D.
Associate Professor
Department of Molecular Cell Biology and Genetics
Graduate School of Biomedical Sciences
UNT Health Science Center
3500 Camp Bowie Blvd, CBH 360
Fort Worth, TX 76107
817-735-2397
