### ISSUE TITLE
Making changes to genepop files

### ISSUE THREAD

**Issue by PatWright** [thibautjombart/adegenet#242]
I'm doing some simulations and my outputs are in genepop format except that my last three loci are  actually additional info on the individual. This means I cannot read them in R. I was wondering if there's  a straightforward way to deal with this issue as I have >5,000 files.

Thanks!

```
bat population at generation 5
A24, B22, CloneA2, Kpa24_2, Mluc8, Kpa16_2, CA38, CA11, Mnatt6, G6, C112_2, MS3D02, H23_Mluc, B23, sex, age, fitness
POP
SubPop0-1, 0406 0506 0103 0707 0407 0608 0909 0810 0507 0404 0305 0714 1213 0614	F	15.0	0.6
SubPop0-2, 0404 0508 0506 0404 0405 0608 0409 0505 0507 0102 0404 0714 0511 1216	M	11.0	0.68
SubPop0-3, 0809 0506 0305 0515 0205 0308 0114 0508 0405 0104 0410 0711 0809 0410	F	10.0	0.7
```

**Comment by zkamvar** [comment]
Hello,

There is no "straightforward" way of going about this. You should use command line tools such as awk and sed to modify your genpop files to the point where you can read them into R with read.csv() and then you will be able to convert them to genind objects with df2genind(). 

Many of the old population genetics formats are fairly terrible ways of storing data, but at least the genepop format is somewhat rectangular so that it shouldn't take too much effort to manipulate it to a standard csv.

**Comment by PatWright** [comment]
Hi,

Thanks for your reply! I don't think it will take that long to do with a command line, I was just hoping that there was a secret command I wasn't aware of.
