### ISSUE TITLE
How to make find.clusters accepts the principle components?

### ISSUE THREAD

**Issue by NamLQ** [thibautjombart/adegenet#288]
Hi!

In some cases, I performed PCA on data and received the principal components (PCs). I would like to use PCs as an input of find.clusters() function. How could I do it?

Thanks!

**Comment by thibautjombart** [comment]
Hi there, 
you have 2 options:
1) pass the `data.frame` containing the PCs to `find.clusters` ; the function will again run a PCA on this input, but since these are already PCs, it won't change a thing
2) if you ran your PCA using `ade4`, use the argument `dudi = your_pca_object`
See `?find.clusters`

**Comment by nicolettacommins** [comment]
I did a PCA using the glPCA function. So should we pass the dataframe containing the PCs (ie. pca$scores) to find.clusters? Elsewhere I saw a comment that we should pass the loadings (ie pca$loadings) to find.clusters so I just want to confirm.
