### ISSUE TITLE
Sorting alleles with read.genetix

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#76]
```r
myFile <- system.file("files/nancycats.gtx",package="adegenet")
cats <- import2genind(myFile)

> alleles(cats)
$fca8
 [1] "135" "143" "133" "137" "141" "129" "131" "145" "123" "139" "147" "149"
[13] "121" "127" "119" "117"

$fca23
 [1] "136" "146" "138" "140" "132" "130" "144" "142" "128" "148" "150"

$fca43
 [1] "139" "145" "141" "149" "135" "137" "133" "147" "143" "157"

$fca45
[1] "116" "120" "126" "128" "130" "118" "132" "122" "134"

$fca77
 [1] "156" "152" "150" "154" "158" "160" "144" "146" "148" "142" "162" "132"

$fca78
[1] "142" "148" "150" "140" "144" "152" "146" "138"

$fca90
 [1] "199" "185" "197" "193" "195" "191" "203" "201" "187" "205" "189" "181"

$fca96
 [1] "113" "091" "105" "101" "121" "107" "109" "115" "117" "103" "111" "119"

$fca37
 [1] "208" "210" "212" "182" "206" "192" "194" "214" "184" "202" "200" "220"
[13] "218" "186" "226" "216" "224" "204"
```

Not sure where the problem comes from, worth checking other import functions.

**Comment by zkamvar** [comment]
This happens with all of the import functions. The feature is in df2genind here: https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L282

The reason this happens is because the function table normally sorts alphabetically, but it could still be erroneous due to the fact that the user could specify a separator with different char lengths for the alleles (e.g. 91/113 instead of 091/113). 

Fixing this is probably best done after the genind object is made with the following steps:

1. sort the alleles by their numeric value within each locus
2. unlist and paste the locus names.
3. rearrange the tab slot by those names.

**Comment by thibautjombart** [comment]
I am no longer sure this is a bug. We have to think alleles can be any characters, not only numbers. Sorting is a bit arbitrary and not really required. But then it triggers very odd things when converting to as.loci - see: https://github.com/emmanuelparadis/pegas/issues/10

**Comment by zkamvar** [comment]
> I am no longer sure this is a bug.

Should we call it a larva? :joy_cat: :bug:

**Comment by aaron-adamack** [comment]
Crossposting this to the link that Thibaut posted above...

I am running into this bug within PopGenReport. The problem seems to originate within the test.polyploid function that is in the hw.test.loci function in pegas. If I have the alleles 174 and 176, the function generates expected probabilities for the genotypes 174/174, 174/176, and 176/176.  The function goes on to generate observed probabilities. If the allele order is 176 followed by 174, it comes up with observed allele frequencies for 174/174, 176/176 and the new allele combination of 176/174. However, it also retains the allele combination of 174/176 resulting in the observed values (O) having 4 values and the expected values (E) having 3 values, leading to the following error message....
Warning messages:
1: In O - E :
  longer object length is not a multiple of shorter object length
2: In (O - E)^2/E :
  longer object length is not a multiple of shorter object length

**Comment by thibautjombart** [comment]
This is definitely an issue with pegas then. Tagging this as issue from somewhere else. Follow-up there:
 https://github.com/emmanuelparadis/pegas/issues/10
