### ISSUE TITLE
ERROR: wrong length for population factor

### ISSUE THREAD

**Issue by sameoldmike** [thibautjombart/adegenet#97]
Hello, I am getting an intractable error using the newest version of adegenet devel in Rstudio 0.99.486:

library(devtools)
install_github("thibautjombart/adegenet")
library("adegenet")
library(hierfstat)
C_3pops = read.genepop("./3_pops_from_PCA.gen", quiet = FALSE)
pairwise.fst(C_3pops[,1:2])

ERROR MESSAGE:
Error in `pop<-`(`*tmp*`, value = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L,  : 
  wrong length for population factor
In addition: Warning message:
In df2genind(tab, ploidy = newPloidy, type = x[[1]]@type, sep = "/") :
  entirely non-type individual(s) deleted

**Comment by jgx65** [comment]
If you check hierfstat on github, we discuss this issue. For teh time being, you should use `hierfstat:genet.dist`with option `method="Nei87"`or `method="WC84"`to get proper pairwise $F_{ST}$

**Comment by sameoldmike** [comment]
Thank you. I was able to use the function you suggested with method="Nei87", although certain loci return an error that cannot be caught with try(). genet.dist() with method="WC84" crashes on each locus. Does it handle missing data encoded as NAs?

The new per-locus values of pairwise Fst are markedly different than I was getting with pairwise.fst() in a previous version of adegenet/hierfstat, but I guess that might be expected since they implement different methods. 


Is this function documented somewhere?

**Comment by jgx65** [comment]
Yes, this point was raised and discussed in the thread.  the help page for `hierfstat::genet.dist` should give you all relevant informations.

**Comment by jgx65** [comment]
@sameoldmike, re the NA and crash, could you provide an example? 

Thanks!

**Comment by thibautjombart** [comment]
Can we have a reproducible example? I want to check that there is no `read.genepop` related error.
Cheers

**Comment by scrameri** [comment]
Hi Thibaut,

Perhapts this helps: I get the same error message using a different function (df2genind). I'm trying to get the SNPs from the (very popular) .vcf format into adegenet as a genind object (for PCA and DAPC reasons since I could not convert .vcf to genlight). It worked fine for a smaller subset of the data (5000 loci), but I get this error when trying it with 30'000 loci. Here is the code run on R version 3-2-1:

require("pegas") # version 0.8-2
require("adegenet") # version 2.0.0
file <- "FilteredSNPs.vcf"
dd <- VCFloci(file) # pegas can read .vcf format
SNP <- is.snp(dd) # determines the SNP subset, ignoring indels etc.
d.snp <- read.vcf(file, which = which(SNP)) # convert "loci, df " format {pegas} to genind {adegenet}
data <- df2genind(d.snp, sep = "/", ncode = 1, NA.char = ".", ploidy = 2, type = "codom") # pop = NULL
Error in 'pop<-'('*tmp*',value = c(11L 14L, 17L, 9L, 4L, 1L, 14L, 14L, :
  wrong length for population factor
In addition: Warning message:
In df2genind(d.snp, sep = "/", ncode = 1, NA.char = ".", ploidy = 2,  :

**Comment by scrameri** [comment]
(cont.) duplicate labels detected for some loci; using generic labels

**Comment by zkamvar** [comment]
Hi @scrameri, I believe the issue you might be encountering is actually related to #101. Can you install the development versions of adegenet and pegas to see if this solves your issue?

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("thibautjombart/adegenet")
devtools::install_github("emmanuelparadis/pegas/pegas")
```

**Comment by scrameri** [comment]
hi @zkamvar, thx for the tip, I'll try it with the dev versions and report again here. Initially, I also tried the loci2genind() function, and noticed the same problem as in #101 concerning the double number of loci, i.e. there was one extra allele in the genind object for every locus that had at least one NA entry. Using df2genind() instead of loci2genind() sorted issue #101 out for me, at least on the smaller dataset where I did not get the error message of this issue.

**Comment by zkamvar** [comment]
The function `head()` will show the first six elements of an object. If you had typed `d.snp` without head, you would have likely seen 47 individuals reported. 

Additionally, for VCF files, there is another package being developed called [vcfR](https://github.com/knausb/vcfR/tree/devel). The development version has tools for conversion to genlight, genind, loci, and DNAbin objects. There are also several vignettes to help you get started.

**Comment by scrameri** [comment]
thank you @zkamvar for the vcfR hint, I'll try that!

**Comment by thibautjombart** [comment]
@scrameri is this problem solved?

**Comment by scrameri** [comment]
Hi, I don't know wheter the "wrong length for population factor" problem is actually solved because I moved on using vcfR and genlight objects get around the error and the long time needed to convert many (>10k) loci into a genind object:

```r
> require("vcfR")
> require("adegenet")
Loading required package: adegenet
Loading required package: ade4

   /// adegenet 2.0.1 is loaded ////////////

   > overview: '?adegenet'
   > tutorials/doc/questions: 'adegenetWeb()' 
   > bug reports/feature requests: adegenetIssues()

# read .vcf file and convert to genlight object
> vcf <- vcfR::read.vcf("path_to_file.vcf")
Meta line 57 read in.
All meta lines processed.
Processed variant: 16087
All variants processed
# data <- vcfR2genind(vcf) # superslow
> data <- vcfR2genlight(vcf) # superfast
Warning message:
In vcfR2genlight(vcf) : Found 801 loci with more than two alleles.
Objects of class genlight only support loci with two alleles.
801 loci will be omitted from the genlight object.
> pop(data) <- factor(dd$Species)

# pca
> glpca <- glPca(data, nf = nf)
> s.class(glpca$scores, pop(data), col=species.col)
> add.scatter.eig(glpca$eig,2,1,2,"topleft")

# dapc
> refdata <- test[subsample] # training dataset
> valdata <- test[-subsample] # validation dataset
> ref.dapc <- dapc(refdata,n.pca=n.pca,n.da=n.da)
> val <- predict(ref.dapc,newdata=valdata)
> table.value(table(val$assign, pop(valdata)), col.lab = levels(pop(valdata))) 
```

**Comment by zkamvar** [comment]
Excellent! @sameoldmike, I believe we are waiting on a reproducible example to see if your issue was related to `read.genepop()`?

**Comment by paquita33** [comment]
Hi, somebody knows how to addition population factor to genind object read from a .vcf file?

**Comment by zkamvar** [comment]
Hi @paquita33, you can store the population factors in a separate spreadsheet and set it as your strata. See the example here: http://popgen.nescent.org/2015-12-15-microsatellite-differentiation.html
